### PR TITLE
chore: support .dat rgb file extension

### PR DESCRIPTION
**Pull request by yuta-tsuzuki-woven**
This change is [Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155)

### CODE REVIEW

**Review by yuta-tsuzuki-woven — COMMENTED** [review]
+@chunleng-woven +@rachel-lien please review it

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155#-:-NYX-5Z39N3dP5YpzDtJ:bclggk6)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chunleng-woven and @rachel-lien)

**Review by chunleng-woven — COMMENTED** [review]
Question, any commands you used to test this?

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155#-:-NYX0YnS-45nS99AsbkU:b-y5pxk5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @rachel-lien)

**Review by yuta-tsuzuki-woven — COMMENTED** [review]
I confirmed it can work with test codes.
I will share it on internal Slack. (It includes some woven internal information) 

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155#-:-NYYDT1vBKhuOlON_8PJ:blisim1)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @chunleng-woven and @rachel-lien)

**Review by rachel-lien — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155#-:-NYZhoqI5_R8bQCBLDoE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chunleng-woven)

**Review by chunleng-woven — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/155#-:-NY_c4DhB14x7W5_TlmS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuta-tsuzuki-woven)

**Pull request merged**
