### PR TITLE
build: split requirements into lib and dev

### PR DESCRIPTION
**Pull request by kenichi-narioka**
This commit splits requirements into dependencies for lib and ones for dev. It allows an external repository that would import dgp to install not all the dependencies but only lib dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96)

### CODE REVIEW

**Review by chrisochoatri — CHANGES_REQUESTED** [review]
+@chrisochoatri review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96#-:-N5qcumY5n62vDzkTWvH:b165z12)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @kenichi-narioka)

___
*[`requirements-dev.txt` line 2 at r2](https://reviewable.io/reviews/tri-ml/dgp/96#-N5qcIqc1UPW6Hwgz0ea:-N5qcIqd2i86T_4lhqP-:b-evphkk) ([raw file](https://github.com/tri-ml/dgp/blob/81a34caaa243d5900e39f722501bbaaf39b2c2cf/requirements-dev.txt#L2)):*
> ```help
> awscli
> Click>=7.1.2
> ```

Click is used in cli.py, should it be it in requirements.txt instead?

**Review by chrisochoatri — COMMENTED** [review]
Thanks Ken, I think you also may need to update the workflow files to make sure they install the correct dependencies and update any potentially update any readmes/documentation .

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96#-:-N5r3bop6hPt0oi8rHcF:b-mgcaxe)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @kenichi-narioka)

**Review by kenichi-narioka — COMMENTED** [review]
Thanks Chris. I've uploaded the workflows. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96#-:-N5rZ5BF0_z1BHtN722p:b-mkcawd)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

___
*[`requirements-dev.txt` line 2 at r2](https://reviewable.io/reviews/tri-ml/dgp/96#-N5qcIqc1UPW6Hwgz0ea:-N5rZ2vt0W3vRGfWk1KS:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/81a34caaa243d5900e39f722501bbaaf39b2c2cf/requirements-dev.txt#L2)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

Click is used in cli.py, should it be it in requirements.txt instead?
</blockquote></details>

Done.

**Review by chrisochoatri — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96#-:-N5rnMfK-nGAuqR6BKTz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenichi-narioka)

**Review by kenichi-narioka — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/96)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenichi-narioka)

**Pull request merged**
