### PR TITLE
schema: add classification annotation type

### PR DESCRIPTION
**Pull request by yuta-tsuzuki-woven**
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83)

### CODE REVIEW

**Review by yuta-tsuzuki-woven — COMMENTED** [review]
Hi @quincy-kh-chen 
I want to add a new annotation type `classification` in `annotations.proto`.
Could you review it and tell me who I should assign as the other reviewer? 
(in my understanding, we need two reviewers for schema PR.)
Thank you in advance.
+@quincy-kh-chen 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83#-:-MzZ1r2BA28ANgkhSJ0a:b-1gug06)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
:lgtm: 
+@chrisochoatri any thoughts? cc @kuanleetri 

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83#-:-Mzr6epN2W0Ppl9itevI:bpnfazr)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 70 at r1](https://reviewable.io/reviews/tri-ml/dgp/83#-Mzr6pcN1iZSZxovGLK0:-Mzr6pcN1iZSZxovGLK1:bqvtlu) ([raw file](https://github.com/tri-ml/dgp/blob/df8e8486a16529aea6ddfb81d71c3bfee5ed0d7c/dgp/proto/annotations.proto#L70)):*
> ```protobuf
>   AGENT_BEHAVIOR = 14;             // agent_behavior
> 
>   // Classification.
> ```

BTW let's elaborate this

for example ` // (i.e. imagenet classification label)`



_Code quote:_
```protobuf
.
```

**Review by yuta-tsuzuki-woven — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/proto/annotations.proto, line 70 at r1](https://reviewable.io/reviews/tri-ml/dgp/83#-Mzr6pcN1iZSZxovGLK0:-MzthFjV3211o4u9ekqY:bvbya2i) ([raw file](https://github.com/tri-ml/dgp/blob/df8e8486a16529aea6ddfb81d71c3bfee5ed0d7c/dgp/proto/annotations.proto#L70)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW let's elaborate this

for example ` // (i.e. imagenet classification label)`
</blockquote></details>

Thank you
Added

**Review by chrisochoatri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83#-:-MzwQu2j3n4Ja7Gh1Eug:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @chrisochoatri and @quincy-kh-chen)

**Review by chrisochoatri — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/83)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yuta-tsuzuki-woven)

**Pull request merged**
