### PR TITLE
fix: fixing the numpy dtype warnings > v1.19

### PR DESCRIPTION
**Pull request by wadimkehl**
This PR fixes some warning we encounter when calling numpy functions. According to numpy, these changes are safe.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/117)

### CODE REVIEW

**Comment by tk-woven** [comment]
FYI the commitlint check requires your commit message to be formatted as

```
type: brief explanation
<empty line>
Longer explanation
```

where type is the usual `feat`, `fix`, `docs`, etc. from [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary).

**Comment by tk-woven** [comment]
I should give an explicit example :)

```
fix: fix the numpy dtype warnings for numpy > v1.19
```

**Comment by wadimkehl** [comment]
Yeah, thanks Tyler. I'm aware that the commitlinter is constantly complaining. I simply do not see where the issue is, as I'm following the template of `type: short description`, and with the long description being optional.

**Review by tk-woven — COMMENTED** [review]
Roger that. Lots of files got reflowed as a result of the pre-commit changes, so the diff is awkward until we rebase. I'll wait to review again until then!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/117#-:-NA6qHTb0juxlS1I-hCF:b-tquc58)* status: 0 of 51 files reviewed, all discussions resolved (waiting on @tk-woven)

**Review by tk-woven — APPROVED** [review]
> Reviewed 5 of 51 files at r1, 46 of 46 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wadimkehl)

**Review by tk-woven — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/117#-:-NA7_E7T1Y__0dR-dzcr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wadimkehl)

**Pull request merged**
