### PR TITLE
feat: update pd_dataset api

### PR DESCRIPTION
**Pull request by chrisochoatri**
This exposes dataset_root and accumulation arguments for the pd dataset classes.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72)

### CODE REVIEW

**Review by chrisochoatri — COMMENTED** [review]
+@visakii-work feature review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72#-:-MqvAEFX9OwSpeYmGp_n:bgesdzo)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @visakii-work)

**Review by visakii-work — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by visakii-work — COMMENTED** [review]
looks good

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72#-:-MqyyMpQ617vukdT3wem:b-47fafm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by visakii-work — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72#-:-Mqz56lXEvtd5ZUJCSgi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/72)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
