### PR TITLE
build: update python lib version for apple silicon

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
- update python grpc versions to be compatible with
  apple silicon
- push *_grpc.py and *_pb2.py generated by updated grpc
- disable jscpd in pre-merge
- clean and rebuild protos for make test
- specify the commit title has to be all lowercase in
  contributing.md
- plintrc to ignore all compiled protos

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/26)

### CODE REVIEW

**Review by quincy-kh-chen — COMMENTED** [review]
+@wadimkehl for review FYI @yuta-tsuzuki-woven 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/26#-:-MlLxfxwBgc1U8v-eIMg:b-gk5ors)* status: 0 of 42 files reviewed, all discussions resolved (waiting on @wadimkehl)

**Comment by wadimkehl** [comment]
Thanks Quincy, immediately run into the next issue. This time it's Cython ;)
Installing with the current version `pip install cython==0.29.11` yields
```
ERROR: Command errored out with exit status 1: /Users/wadimkehl/miniforge3/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ww/k_v081l90pd2g8fwffhll36r0000gn/T/pip-install-6pippf_6/cython_2d6d233324f4432aae30e4baab517369/setup.py'"'"'; __file__='"'"'/private/var/folders/ww/k_v081l90pd2g8fwffhll36r0000gn/T/pip-install-6pippf_6/cython_2d6d233324f4432aae30e4baab517369/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/ww/k_v081l90pd2g8fwffhll36r0000gn/T/pip-record-98maqkpg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/wadimkehl/miniforge3/include/python3.9/cython Check the logs for full command output.
```
whereas 
`pip install cython==0.29.11`
installs correctly.

**Review by quincy-kh-chen — COMMENTED** [review]
Hi @wadimkehl, updated `cython==0.29.21`. It works on my ubuntu and macOS machines. Let's see if it passes CI.

> Reviewed 2 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/26#-:-MlMyFoWEpjQglOPsjuM:bqlelgq)* status: 2 of 44 files reviewed, all discussions resolved (waiting on @wadimkehl)

**Review by wadimkehl — APPROVED** [review]
:lgtm:

> Reviewed 35 of 42 files at r1, 3 of 7 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/26#-:-MlNZo8K3B67OGd_8Kod:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Pull request merged**
