### PR TITLE
fix: update python version and fix bug in vis test

### PR DESCRIPTION
**Pull request by chrisochoatri**
This upgrades python to 3.7 in the base docker and fixes a small bug in the visualization engine test

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)

### CODE REVIEW

**Review by kuanleetri — APPROVED** [review]
:lgtm:
Any reason to update to 3.7?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85#-:-N-jVNdS1qsg3Ot8P4Yo:b-kw1xyx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
3.6 is end of life as of Dec 21, time to upgrade. I have no specific reason for 3.7 vs 3.9 or 3.10 though. Any thoughts?

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85#-:-N-jahed6d4f839F7x9z:bl4rb35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by quincy-kh-chen — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by quincy-kh-chen — DISMISSED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85#-:-N0C04Is4YBx2iaYlZM1:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85#-:-N0E0Zhl0LZX8YIeafj-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — APPROVED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by kuanleetri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
