### PR TITLE
docs: update homepage and contributing.md

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
- update README.md and CONTRIBUTING.md
- update code coverage threshold to 39

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60)

### CODE REVIEW

**Review by quincy-kh-chen — COMMENTED** [review]
+@sshusaintri for review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60#-:-Moo_80B3HOinn9Njy4W:beelk1q)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @sshusainTRI)

**Review by sshusainTRI — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen and @sshusainTRI)

___
*[docs/CONTRIBUTING.md, line 125 at r1](https://reviewable.io/reviews/tri-ml/dgp/60#-Mooc87E6-nqTKyZ_UJv:-Mooc87E6-nqTKyZ_UJw:b-wss1vb) ([raw file](https://github.com/tri-ml/dgp/blob/c89399c933f07192067af4fae205420be756029a/docs/CONTRIBUTING.md#L125)):*
> ```Markdown
> ### Test Coverage Policy
> 
> In General, features (`feat`) commits should include test cases. Test cases should be based on unittest.
> ```

Test cases should probably now be based on pytest, not unittest

**Review by sshusainTRI — CHANGES_REQUESTED** [review]
Just 1 feedback in reviewable regarding documentation

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @sshusainTRI)

___
*[docs/CONTRIBUTING.md, line 125 at r1](https://reviewable.io/reviews/tri-ml/dgp/60#-Mooc87E6-nqTKyZ_UJv:-MoooffnDwFvAyNgjPZO:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/c89399c933f07192067af4fae205420be756029a/docs/CONTRIBUTING.md#L125)):*
<details><summary><i>Previously, sshusainTRI wrote…</i></summary><blockquote>

Test cases should probably now be based on pytest, not unittest
</blockquote></details>

Done.

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @sshusainTRI)

**Review by sshusainTRI — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60#-:-Mop6iIVCqDNEayZQUFP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sshusainTRI)

**Review by sshusainTRI — APPROVED** [review]

**Review by sshusainTRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Pull request merged**
