### PR TITLE
feat: expose disk cache setting to synchronized and pd datasets

### PR DESCRIPTION
**Pull request by chrisochoatri**
- This allows users to specify if they want to use the scene disk cache when memory is not a concern. 
- Also adds some minor format changes and silences a pylint warning.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)

### CODE REVIEW

**Review by quincy-kh-chen — DISMISSED** [review]
> put a Note here to warn user to switch to False when RAM is small
:lgtm: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74#-:-Mr9Rog95JOGaRyrobeW:b-qz259t)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

___
*[dgp/datasets/pd_dataset.py, line 250 at r1](https://reviewable.io/reviews/tri-ml/dgp/74#-Mr9Rhcz6xQV7SOLB8-l:-Mr9Rhcz6xQV7SOLB8-m:b-vb2mb8) ([raw file](https://github.com/tri-ml/dgp/blob/c65dde0c370d3e5363c320d15ffa90dcdf5e086a/dgp/datasets/pd_dataset.py#L250)):*
> ```Python
>         dataset_root=None,
>         transform_accumulated_box_points=False,
>         use_diskcache=True,
> ```

BTW put a Note here to warn user to switch to False when RAM is small

**Review by chrisochoatri — COMMENTED** [review]
done, added to synchronized, pd, and frame datasets.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74#-:-Mr9UkkS7rOkqWkUvTcU:b1h9dst)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

___
*[dgp/datasets/pd_dataset.py, line 250 at r1](https://reviewable.io/reviews/tri-ml/dgp/74#-Mr9Rhcz6xQV7SOLB8-l:-Mr9UiFD2poqQADuNutN:bb7f2mf) ([raw file](https://github.com/tri-ml/dgp/blob/c65dde0c370d3e5363c320d15ffa90dcdf5e086a/dgp/datasets/pd_dataset.py#L250)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW put a Note here to warn user to switch to False when RAM is small
</blockquote></details>

done

**Review by quincy-kh-chen — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74#-:-Mr9V-PB96XMOWaTlVhN:bg7igkv)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74#-:-Mr9nLvs5GCCucTG6cMv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Review by quincy-kh-chen — APPROVED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
