### PR TITLE
v1.0 public release

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
This release includes v1.0 components of internal TRI DGP:

- Protos
- DatasetClass (Synchronized, Frame)
- CLI with visualizer

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)

### CODE REVIEW

**Review by quincy-kh-chen — COMMENTED** [review]
+@yuta-tsuzuki-woven for review FYI @kuanleetri @wadimkehl 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20#-:-MkiOI1d1WhsMEEQcJPG:b-z0ob34)* status: 0 of 90 files reviewed, all discussions resolved (waiting on @yuta-tsuzuki-woven)

**Review by wadimkehl — CHANGES_REQUESTED** [review]
Thanks Quincy, it's a piece of art :) :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20#-:-Mkit4bFDeHLhp2Fi8mz:bagszqs)* status: 0 of 90 files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen and @yuta-tsuzuki-woven)

___
*[dgp/datasets/base_dataset.py, line 689 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkicChMBK6-7A22H_qt:-MkicChMBK6-7A22H_qu:bcy59pw) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/datasets/base_dataset.py#L689)):*
> ```Python
>         # Check datum names, and normalize them.
>         if not isinstance(datum_names, (tuple, list)):
>             import pdb
> ```

This debug stuff should probably not be here ;)

**Review by yuta-tsuzuki-woven — CHANGES_REQUESTED** [review]
Thank you @quincy-kh-chen!
I added some minor comments

> Reviewed 90 of 90 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20#-:-Mkiw-yt1pjBA2LPUiw4:b-se5s89)* status: all files reviewed, 4 unresolved discussions (waiting on @quincy-kh-chen)

___
*[dgp/__init__.py, line 27 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkioTZJ0EhBl4XV7T2w:-MkioTZK7VEHhaJgjTOW:b-8waiut) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/__init__.py#L27)):*
> ```Python
> INSTANCE_SEGMENTATION_2D_FOLDER = 'instance_segmentation_2d'
> INSTANCE_SEGMENTATION_3D_FOLDER = 'instance_segmentation_3d'
> DEPTH_FOLDER = 'depth'
> ```

Nit, are the following parameters missing?
```
RADAR_POINT_CLOUD_FOLDER = "radar_point_cloud"
EXTRA_DATA_FOLDER = "extra_data"
```
___
*[dgp/proto/scene.proto, line 38 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkirrTB6_6zjVWnnSot:-MkirrTB6_6zjVWnnSou:bn2h5cq) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/proto/scene.proto#L38)):*
BTW, does this convertor exist in this repository?

> ```
> tlog_to_scale_converter
> ```
___
*[dgp/utils/dataset_conversion.py, line 274 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkiq1oY4WaeGzb_a5xd:-Mkiq1oZ-DXZWPWxMzvZ:b-mm80te) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/dataset_conversion.py#L274)):*
> ```Python
>     timestamp = Timestamp()
>     timestamp.GetCurrentTime()
>     return timestamp
> ```

Are the following classes missing?
```
class DatasetGen
class MergeSceneDatasetGen
class SlimSnapshotDatasetGen(DatasetGen)
```
___
*[dgp/utils/protobuf.py, line 36 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkihww95Yf1QRzTGX_d:-Mkihww95Yf1QRzTGX_e:b-ikhyug) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/protobuf.py#L36)):*
> ```Python
>     assert os.path.exists(path), f'Path not found: {path}'
>     with open(path, 'r') as json_file:
>         pb_object = Parse(json_file.read(), pb_class())
> ```

BTW, is `open_remote_pb_object(s3_object_uri, pb_class)` method missing?
https://github.toyota-stargate.tech/toyota-group/ouroboros/blob/master/ouroboros/dgp/utils/protobuf.py#L44

and also `get_latest_scene(s3_scene_jsons)` method is missing?
___
*[dgp/utils/structures/__init__.py, line 1 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkit2k_EWf7y3os17in:-Mkit2k_EWf7y3os17io:b-se2j8x) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/structures/__init__.py#L1)):*
> ```Python
> # Copyright 2020 Toyota Research Institute. All rights reserved.
> ```

Nit, 2020 -> 2021?

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 85 of 90 files reviewed, 3 unresolved discussions (waiting on @wadimkehl and @yuta-tsuzuki-woven)

___
*[dgp/__init__.py, line 27 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkioTZJ0EhBl4XV7T2w:-MkjT1YR99sohLHtVsJk:bsygeju) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/__init__.py#L27)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

Nit, are the following parameters missing?
```
RADAR_POINT_CLOUD_FOLDER = "radar_point_cloud"
EXTRA_DATA_FOLDER = "extra_data"
```
</blockquote></details>

Good catch! Added.
___
*[dgp/datasets/base_dataset.py, line 689 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkicChMBK6-7A22H_qt:-MkjT4LA2a534qF0NQ9l:b-4grvzq) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/datasets/base_dataset.py#L689)):*
<details><summary><i>Previously, wadimkehl (Wadim Kehl) wrote…</i></summary><blockquote>

This debug stuff should probably not be here ;)
</blockquote></details>

Good catch! Removed.
___
*[dgp/proto/scene.proto, line 38 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkirrTB6_6zjVWnnSot:-MkjT8Tj2bxwsZFvD_Kx:btn95w3) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/proto/scene.proto#L38)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

BTW, does this convertor exist in this repository?

> ```
> tlog_to_scale_converter
> ```

</blockquote></details>

No. Removed the comments.
___
*[dgp/utils/dataset_conversion.py, line 274 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkiq1oY4WaeGzb_a5xd:-MkjTDSu-k3z_9Q6RVLq:b-r2x1gt) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/dataset_conversion.py#L274)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

Are the following classes missing?
```
class DatasetGen
class MergeSceneDatasetGen
class SlimSnapshotDatasetGen(DatasetGen)
```
</blockquote></details>

Yes, we decided to remove DatasetGen in this release. Is this something needed from your end?
___
*[dgp/utils/protobuf.py, line 36 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkihww95Yf1QRzTGX_d:-MkjTQHr6cr8h2JHAv7B:b5lqzmw) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/protobuf.py#L36)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

BTW, is `open_remote_pb_object(s3_object_uri, pb_class)` method missing?
https://github.toyota-stargate.tech/toyota-group/ouroboros/blob/master/ouroboros/dgp/utils/protobuf.py#L44

and also `get_latest_scene(s3_scene_jsons)` method is missing?
</blockquote></details>

Yes, we decided to decouple AWS dependency from DGP. Is this heavily being used by Woven?

**Review by yuta-tsuzuki-woven — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 89 of 90 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen, @wadimkehl, and @yuta-tsuzuki-woven)

___
*[dgp/utils/dataset_conversion.py, line 274 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkiq1oY4WaeGzb_a5xd:-MkjW5p8348xRXkpsYjo:b-q9zkct) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/dataset_conversion.py#L274)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Yes, we decided to remove DatasetGen in this release. Is this something needed from your end?
</blockquote></details>

We are using `DatasetGen ` as a base class when we create DGP dataset.
If you can keep this class, it's very helpful for us.
___
*[dgp/utils/protobuf.py, line 36 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkihww95Yf1QRzTGX_d:-MkjUhYPAq8ls3_HXUfb:biikmia) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/protobuf.py#L36)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Yes, we decided to decouple AWS dependency from DGP. Is this heavily being used by Woven?
</blockquote></details>

I see
We are using `open_remote_pb_object(s3_object_uri, pb_class)` method but we can easily modify it in our side so it's not a big problem.

**Review by kuanleetri — COMMENTED** [review]
> Reviewed 3 of 90 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 89 of 90 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen, @wadimkehl, and @yuta-tsuzuki-woven)

___
*[dgp/datasets/base_dataset.py, line 689 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkicChMBK6-7A22H_qt:-MkmI9mn3-Qm7zgI2O1n:b2ni78k) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/datasets/base_dataset.py#L689)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Good catch! Removed.
</blockquote></details>

lol

**Review by kuanleetri — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 89 of 90 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen, @wadimkehl, and @yuta-tsuzuki-woven)

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 89 of 90 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen, @wadimkehl, and @yuta-tsuzuki-woven)

___
*[dgp/datasets/base_dataset.py, line 689 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-MkicChMBK6-7A22H_qt:-MkmUsTrDZLKMgvaFcJ2:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/datasets/base_dataset.py#L689)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

lol
</blockquote></details>

Done.

**Review by kuanleetri — COMMENTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: all files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen and @wadimkehl)

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: all files reviewed, 2 unresolved discussions (waiting on @wadimkehl and @yuta-tsuzuki-woven)

___
*[dgp/utils/dataset_conversion.py, line 274 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkiq1oY4WaeGzb_a5xd:-Mkmpyrv319smGtujIeq:b39neh3) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/dataset_conversion.py#L274)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

We are using `DatasetGen ` as a base class when we create DGP dataset.
If you can keep this class, it's very helpful for us.
</blockquote></details>

Thanks for the suggestion. Added `DatasetGen` and `MergeSceneDatasetGen`
___
*[dgp/utils/protobuf.py, line 36 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkihww95Yf1QRzTGX_d:-Mkmpoxc9swHpjvknlu7:bqnrimn) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/protobuf.py#L36)):*
<details><summary><i>Previously, yuta-tsuzuki-woven wrote…</i></summary><blockquote>

I see
We are using `open_remote_pb_object(s3_object_uri, pb_class)` method but we can easily modify it in our side so it's not a big problem. 
</blockquote></details>

Added this function since `DatasetGen` also relies on these s3 utils.

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: all files reviewed, 2 unresolved discussions (waiting on @wadimkehl and @yuta-tsuzuki-woven)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 84 of 93 files reviewed, 2 unresolved discussions (waiting on @wadimkehl and @yuta-tsuzuki-woven)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: 83 of 93 files reviewed, 2 unresolved discussions (waiting on @wadimkehl and @yuta-tsuzuki-woven)

**Review by yuta-tsuzuki-woven — APPROVED** [review]
:lgtm: with a minor comment

> Reviewed 8 of 9 files at r3, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20#-:-MknutWa70b6oWCIf6PS:b-cttxx2)* status: all files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen and @wadimkehl)

___
*[dgp/utils/dataset_conversion.py, line 274 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkiq1oY4WaeGzb_a5xd:-Mkntvxv2uv-cGHElSNL:b-9755fn) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/dataset_conversion.py#L274)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Thanks for the suggestion. Added `DatasetGen` and `MergeSceneDatasetGen`
</blockquote></details>

Thank you!
___
*[dgp/utils/dataset_conversion.py, line 285 at r5](https://reviewable.io/reviews/tri-ml/dgp/20#-Mknu7pN7unCXsJZOpLk:-Mknu7pO7yrikcndCeRV:b-mzjion) ([raw file](https://github.com/tri-ml/dgp/blob/113aa94cd5053cfa74094cc21196d2941a0a06b5/dgp/utils/dataset_conversion.py#L285)):*
> ```Python
>     DESCRIPTION = ""
>     PUBLIC = True
>     EMAIL = "ml@tri.global"
> ```

Nit, is it ok to describe tri email here?
___
*[dgp/utils/protobuf.py, line 36 at r1](https://reviewable.io/reviews/tri-ml/dgp/20#-Mkihww95Yf1QRzTGX_d:-Mknuays2D8a_Hd1LhzZ:b-9755fn) ([raw file](https://github.com/tri-ml/dgp/blob/389b720044fbaad768344fbcbd975efb8e51f504/dgp/utils/protobuf.py#L36)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Added this function since `DatasetGen` also relies on these s3 utils.
</blockquote></details>

Thank you!

**Review by wadimkehl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20#-:-Mknyg-uBex3USmOvBrJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/20)* status: all files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen)

**Pull request merged**
