### PR TITLE
ci: add pre-merge github action workflow

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
- add pre-merge tests to github action
- add formatting, linting, commitlint checks
- fix linting errors
- update readme
- update yapf to 0.31.0

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/21)

### CODE REVIEW

**Review by quincy-kh-chen — COMMENTED** [review]
+ @kuanleetri for review FYI @yuta-tsuzuki-woven  

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/21#-:-MkxY2Xa32mYNB7n7jxj:bqhmrgu)* status: 0 of 16 files reviewed, all discussions resolved

**Review by kuanleetri — COMMENTED** [review]
:lgtm:
See many reformatting, do u use the .style.yapf?

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/21#-:-MlCPepS7dllRFQlZ5T_:b-spjmyx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
Yes, might have to open another PR to fix all linting/formatting issues since we update the linter/formatter versions.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/21#-:-MlGDg4Q5v4nwqNCiV1N:be3vngr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by kuanleetri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/21#-:-MlGNUgM5HWR7vY8l_By:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Pull request merged**
