### PR TITLE
feat: replace last SuperLinter check `yamllint` with pre-commit hook

### PR DESCRIPTION
**Pull request by tk-woven**
# Description

This concludes #114 . This introduces the `yamllint` pre-commit hook, runs it on all files, and touches up some violations. It also introduces a configuration for `yamllint` to ignore some checks that we don't need or otherwise modify them.

This is the last SuperLinter check to migrate, so this work also removes SuperLinter from CI.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/124)

### CODE REVIEW

**Review by wadimkehl — APPROVED** [review]
Thanks. I hope we can move fast on this one. The SuperLinter is a nightmare

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/124#-:-N9ukt6x1cckiwNPqjO_:b-rjwyat)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tk-woven)

**Review by tk-woven — COMMENTED** [review]
Thanks! I had to rebase on master but otherwise am good-to-go now.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/124#-:-NA6pViVDcVbArjH-j3p:b-d14rwu)* status: 7 of 15 files reviewed, all discussions resolved (waiting on @chrisochoatri, @kuanleetri, and @wadimkehl)

**Comment by wadimkehl** [comment]
Still unresolved conflicts?

**Comment by tk-woven** [comment]
Odd; there were some diffs in your recent merges to the conflicting files. Those diffs came from my previously-merged commits. Not sure what's going on here, but yes, more conflicts that I'll resolve!

**Comment by tk-woven** [comment]
I see, it was the combination of my changes reflowing some YAML and your changes bumping the Python version in them :)

**Review by wadimkehl — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/124#-:-NA83MkA2iZ3n21q_fI0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri and @kuanleetri)

**Pull request merged**
