### PR TITLE
style: modify parallel domain metadata with `make build-proto`

### PR DESCRIPTION
**Pull request by nehalmamgain**
I made a virtual environment following `pip install -r requirements-dev.txt`
(Also tested this in the virtual environment following [this](https://github.com/TRI-ML/dgp/blob/master/docs/VIRTUAL_ENV.md).)

Although not documented in [CONTRIBUTING](https://github.com/TRI-ML/dgp/blob/db695a28ab9ace12d743e766b808238478365856/docs/CONTRIBUTING.md) (fixed now with https://github.com/TRI-ML/dgp/pull/103), one of the former DGP maintainers asked to run `make build-proto` on [this PR](https://github.com/TRI-ML/dgp/pull/45).

When running make build-proto, I saw a [previous commit](https://github.com/TRI-ML/dgp/pull/87) I made be formatted differently.
This PR commits the affected file with the output of `make build-proto` so that other users don't see a file unrelated to their PR also show up in their `git status` when contributing to this repository.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102)

### CODE REVIEW

**Comment by nehalmamgain** [comment]
+reviewer:@tk-woven +reviewer:@kuanleetri

**Comment by nehalmamgain** [comment]
I edited the commit message to follow linter expectations

**Review by tk-woven — COMMENTED** [review]
Thanks! The generated file was built from the source tree as-is, no local changes?

We can probably extend DGP CI to build the protos and make sure everything us up to date as one of the checks.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102#-:-N8Mrsx91827kUY6fg07:bilmvjg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Comment by nehalmamgain** [comment]
> The generated file was built from the source tree as-is, no local changes?

Yup, exactly!

> We can probably extend DGP CI to build the protos and make sure everything us up to date as one of the checks.

That sounds cool!

The CI failed. I don't believe the test is related to PD metadata though. Temporary failure (since it actually [passed](https://github.com/TRI-ML/dgp/actions/runs/2772457685) before; twice!)?
@tk-woven Sorry to bother you, but I don't have access to re-run this workflow without pushing a change. Could you please re-run it?

```
=================================== FAILURES ===================================
______________________ TestTorchUtilities.test_pose_utils ______________________

self = <tests.test_torch_extension_utils.TestTorchUtilities testMethod=test_pose_utils>

    def test_pose_utils(self):
        """Test pose class in dgp.utils.torch_extension.Pose and dgp.utils.torch_extension.QuaternionPose"""
    
        # Test pose transforms
        npposes = [NumpyPose(wxyz=pvec[:4], tvec=pvec[4:]) for pvec in self.pvecs]
        poses = [Pose(tf) for tf in self.tfs]
        qposes = [QuaternionPose.from_matrix(tf) for tf in self.tfs]
    
        # Test matrix composition of transformations
        final_pose_np = functools.reduce(lambda x, y: x @ y, [tf.numpy() for tf in self.tfs])
        final_pose_torch = functools.reduce(lambda x, y: x @ y, self.tfs)
        assert_true(np.allclose(final_pose_np, final_pose_torch.numpy(), atol=1e-6))
    
        # Test Pose manifold composition of transformations
        final_pose_NumpyPose = functools.reduce(lambda x, y: x * y, npposes)
        final_pose_Pose = functools.reduce(lambda x, y: x * y, poses)
        final_pose_QuaternionPose = functools.reduce(lambda x, y: x * y, qposes)
        assert_true(np.allclose(final_pose_np, final_pose_NumpyPose.matrix, atol=1e-6))
        assert_true(np.allclose(final_pose_np, final_pose_Pose.matrix.numpy(), atol=1e-6))
        assert_true(np.allclose(final_pose_np, final_pose_QuaternionPose.matrix.numpy(), atol=1e-6))
    
        def make_random_points(B=1, N=100):
            return torch.from_numpy(np.random.rand(B, 3, N)).type(torch.float)
    
        # Test single point cloud transformations for some implementations
        X = make_random_points()
        Xt_ = X[0].numpy()
        X_ = Xt_.T
    
        # Test point cloud transformations
        X1 = final_pose_Pose * X
        X2 = final_pose_QuaternionPose * X
        X3 = final_pose_NumpyPose * X_
        X4 = final_pose_np.dot(np.vstack([Xt_, np.ones((1, len(X_)))]))
    
>       assert_true(np.allclose(X1.numpy(), X2.numpy(), atol=1e-6))
E       AssertionError: False is not true

tests/test_torch_extension_utils.py:98: AssertionError
=========================== short test summary info ============================
FAILED tests/test_torch_extension_utils.py::TestTorchUtilities::test_pose_utils
=================== 1 failed, [57](https://github.com/TRI-ML/dgp/runs/7604952531?check_suite_focus=true#step:7:58) passed, 1 skipped in 41.[76](https://github.com/TRI-ML/dgp/runs/7604952531?check_suite_focus=true#step:7:77)s ===================
```

**Comment by tk-woven** [comment]
Re-running now!

**Comment by nehalmamgain** [comment]
Thank you, the coverage test passed. Please re-review :bowing_woman:

**Review by tk-woven — APPROVED** [review]
Thanks, :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102#-:-N8N0MwAEn-TmS45BtND:bwq6wfm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Comment by nehalmamgain** [comment]
I'll leave it up to you and @kuanleetri to merge this, thanks!

**Comment by tk-woven** [comment]
Got it! I'm not very familiar with this process yet. @kuanleetri , I'd like your input if you have a moment. If some time passes and I can study this process for myself, I'll merge it on my own :)

**Comment by nehalmamgain** [comment]
@tk-woven Btw could you please support here and check the merge process/reach out to @kuanleetri ?
It's not so important to get this PR merged but it's extremely important to merge https://github.com/TRI-ML/dgp/pull/101 .

**Review by tk-woven — APPROVED** [review]
I think we understand the merge process. What we're asking for here is Kuan's review since I'm not familiar with this part of the development. I will need to take some time to familiarize myself, but that has to wait for some other work I'm in the middle of. If you need to reach Kuan, please kindly try Slack (I have no special powers in this regard).

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102#-:-N8WtJZ77WpwM9twhlUW:b-yfbec4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Review by tk-woven — APPROVED** [review]
Nehal, I ran through the steps myself. Your work here LGTM! Can you please update your branch? Then when CI passes I can merge :)

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102#-:-N8X_fzT9MsCqZ6PTu-s:b-rfv4x7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Review by wadimkehl — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Comment by nehalmamgain** [comment]
Rebased off of master.

**Review by wadimkehl — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/102#-:-N8fpCoU5e-cogmc8xC1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Pull request merged**
