### PR TITLE
ci: updating packages to downstream, including Ubuntu20 and py39

### PR DESCRIPTION
**Pull request by wadimkehl**
Bringing this repo up to speed with the rest of the ecosystem.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/125)

### CODE REVIEW

**Review by tk-woven — CHANGES_REQUESTED** [review]
Nice; thanks so much!

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/125#-:-N9hqlVjBvVcT8rcS_Hf:b-d9s7cw)* status: all files reviewed, 2 unresolved discussions (waiting on @wadimkehl)

___
*[`Dockerfile` line 36 at r2](https://reviewable.io/reviews/tri-ml/dgp/125#-N9hpzJu1XzoV_8XiJc7:-N9hpzJu1XzoV_8XiJc8:b-fqoiye) ([raw file](https://github.com/tri-ml/dgp/blob/0255548e384051e0f38e45892f4f0f1e4b50a5b7/Dockerfile#L36)):*
> ```Dockerfile
>   rm get-pip.py
> # The above appears to install pip into /usr/local/, but some tools expect /usr/bin/.
> # TODO(tk-woven): `apt install python3-pip` and remove these symlinks when we update the base Ubuntu image.
> ```

Since we're skipping the distro-default 3.8, let's just remove the second line of this comment now please. (The first line is still relevant.)
___
*[`requirements.txt` line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/125#-N9hqBzo8vYHqsMA6Spi:-N9hqBzo8vYHqsMA6Spj:b-i5l98f) ([raw file](https://github.com/tri-ml/dgp/blob/0255548e384051e0f38e45892f4f0f1e4b50a5b7/requirements.txt#L9)):*
> ```help
> Pillow>=8.3.2
> pycocotools>=2.0.0
> pyquaternion==0.9.9 
> ```

Do we need this specific version? If not, let's go with `pyquaternion>=0.9.5,<=1.0.0` to allow more end-user flexibility.

**Review by wadimkehl — COMMENTED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/125#-:-N9uZE9SAnTWzngmLpfM:b-ucfknh)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @tk-woven)

___
*[`Dockerfile` line 36 at r2](https://reviewable.io/reviews/tri-ml/dgp/125#-N9hpzJu1XzoV_8XiJc7:-N9uZCwmCZ8VSMTHxIMU:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/0255548e384051e0f38e45892f4f0f1e4b50a5b7/Dockerfile#L36)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Since we're skipping the distro-default 3.8, let's just remove the second line of this comment now please. (The first line is still relevant.)
</blockquote></details>

Done.
___
*[`requirements.txt` line 9 at r2](https://reviewable.io/reviews/tri-ml/dgp/125#-N9hqBzo8vYHqsMA6Spi:-N9uZDkN8uOTmW1kZPjL:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/0255548e384051e0f38e45892f4f0f1e4b50a5b7/requirements.txt#L9)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Do we need this specific version? If not, let's go with `pyquaternion>=0.9.5,<=1.0.0` to allow more end-user flexibility.
</blockquote></details>

Done.

**Review by tk-woven — APPROVED** [review]
Thanks! :lgtm: 

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/125#-:-NA6ovEb0qtfwEwLjL-W:b6duv8n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wadimkehl)

**Review by tk-woven — APPROVED** [review]
Thanks!

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/125#-:-NA7ALeq79t_rf9lmqsS:b-ucfknh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wadimkehl)

**Pull request merged**
