### PR TITLE
test: increase test coverage thresh to 46

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)

### CODE REVIEW

**Review by quincy-kh-chen — COMMENTED** [review]
+@sshusaintri for review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77#-:-Mt9vUki8seL6NySour0:beelk1q)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @sshusainTRI)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sshusainTRI)

**Review by sshusainTRI — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77#-:-MtA4IbX93zo-qGYbCY2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by sshusainTRI — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)* status: all files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen)

___
*[.github/workflows/coverage.yml, line 15 at r1](https://reviewable.io/reviews/tri-ml/dgp/77#-MtA4N_E1pslio6SqN4a:-MtA4N_E1pslio6SqN4b:b-wfic5a) ([raw file](https://github.com/tri-ml/dgp/blob/d60e0f76ae74726378dbac4614e2614701c84b95/.github/workflows/coverage.yml#L15)):*
> ```YAML
>       OS: ubuntu-18.04
>       PYTHON: '3.6'
>       COVERAGE_TOTAL: 47 # Coverage threshold percentage
> ```

You may want to set this to 46 instead, just to account for rounding

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @quincy-kh-chen and @sshusainTRI)

___
*[.github/workflows/coverage.yml, line 15 at r1](https://reviewable.io/reviews/tri-ml/dgp/77#-MtA4N_E1pslio6SqN4a:-MtA5ZrBBI2kG8ADWJq2:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/d60e0f76ae74726378dbac4614e2614701c84b95/.github/workflows/coverage.yml#L15)):*
<details><summary><i>Previously, sshusainTRI wrote…</i></summary><blockquote>

You may want to set this to 46 instead, just to account for rounding 
</blockquote></details>

Done.

**Review by sshusainTRI — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77#-:-MtA5oTJ38vrRwAsCo7N:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @quincy-kh-chen and @sshusainTRI)

**Review by sshusainTRI — APPROVED** [review]

**Review by sshusainTRI — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/77)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Pull request merged**
