### PR TITLE
fix: Update requirements.txt

### PR DESCRIPTION
**Pull request by wadimkehl**
Updating the xarray to the latest version

- - -
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/111)

### CODE REVIEW

**Comment by tk-woven** [comment]
Looks like we might have to update the Docker image to Ubuntu 20 to pass CI, assuming that's what's holding pip back from finding the latest `xarray` version. I don't mind updating the base image tomorrow, but feel free to give it a go if you'd like!

**Comment by wadimkehl** [comment]
It seems that xarray 2022.6 requires python>=3.8, so we need to wait until my other PR lands in master.

**Comment by tk-woven** [comment]
Roger that, waiting on #125 .

**Review by tk-woven — APPROVED** [review]
:lgtm: BTW, #124 is good to go, too.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/111#-:-NA7PmOWD5yJCOfBA6ow:bev7urs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kuanleetri)

**Pull request merged**
