### PR TITLE
fix: speed up base dataset init

### PR DESCRIPTION
**Pull request by quincy-kh-chen**
- remove unused variable annotation_index

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)

### CODE REVIEW

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[tests/test_datasets_timeout.py, line 1 at r2](https://reviewable.io/reviews/tri-ml/dgp/73#-Mr9DRyw18qrUUoJr3lo:-Mr9DRyw18qrUUoJr3lp:b-9rjhzg) ([raw file](https://github.com/tri-ml/dgp/blob/2d1b0e1024211ec43dbedf30d624e859c9ee9334/tests/test_datasets_timeout.py#L1)):*
> ```Python
> # TODO: merge this test into tests/test_datasets.py once it migrats to pytest.
> ```

nit: copyright notice?

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[tests/test_datasets_timeout.py, line 52 at r2](https://reviewable.io/reviews/tri-ml/dgp/73#-MrAY4oG0xLs4oTIMhlp:-Mr6GzQI3XYAVtAD3ukk:b-2wnya1) ([raw file](https://github.com/tri-ml/dgp/blob/2d1b0e1024211ec43dbedf30d624e859c9ee9334/tests/test_datasets_timeout.py#L52)):*
> ```Python
> 
>     scenes_dataset_json = os.path.join(os.path.join(TEST_DATA_DIR, "dgp"), "test_scene", "scene_dataset_v1.0.json")
>     for _ in range(10):
> ```

nit: not related to this PR, but could you add a test case without the scene cache? ie use_diskcache=False. Just a curiosity

**Review by quincy-kh-chen — COMMENTED** [review]
+@chrisochoatri for review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73#-:-MrO45329uyX7ttAn0ni:biqrhe5)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

___
*[tests/test_datasets_timeout.py, line 52 at r2](https://reviewable.io/reviews/tri-ml/dgp/73#-MrAY4oG0xLs4oTIMhlp:-MrO5Rx34bFOMBcZqrGR:bjr5blj) ([raw file](https://github.com/tri-ml/dgp/blob/2d1b0e1024211ec43dbedf30d624e859c9ee9334/tests/test_datasets_timeout.py#L52)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

nit: not related to this PR, but could you add a test case without the scene cache? ie use_diskcache=False. Just a curiosity 
</blockquote></details>

This actually won't have an impact on dataset class object creation. It will change dataset iteration speed. Maybe we can add more throughout timing tests for dataset iteration later!

**Review by quincy-kh-chen — COMMENTED** [review]
FYI @sshusaintri adding some timing tests in this PR

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73#-:-MrO5mpu1GxjW2--B9j2:b78wpez)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

**Review by chrisochoatri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[tests/test_datasets_timeout.py, line 1 at r2](https://reviewable.io/reviews/tri-ml/dgp/73#-MrO5bQ-3rMCicfHlA0A:-MrO5bQ0CEK4d_nuGa3W:b57h8db) ([raw file](https://github.com/tri-ml/dgp/blob/2d1b0e1024211ec43dbedf30d624e859c9ee9334/tests/test_datasets_timeout.py#L1)):*
> ```Python
> # TODO: merge this test into tests/test_datasets.py once it migrats to pytest.
> ```

s/migrats/migrates

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[tests/test_datasets_timeout.py, line 1 at r2](https://reviewable.io/reviews/tri-ml/dgp/73#-MrO5bQ-3rMCicfHlA0A:-MrO65W553DHB8PggZ5Z:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/2d1b0e1024211ec43dbedf30d624e859c9ee9334/tests/test_datasets_timeout.py#L1)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

s/migrats/migrates
</blockquote></details>

Done.

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @chrisochoatri)

**Review by chrisochoatri — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73#-:-MrO6boe9ajHJ_QFqoFq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Pull request merged**
