### PR TITLE
feat: add ability to load autolabels

### PR DESCRIPTION
**Pull request by chrisochoatri**
This adds the ability to load autolabel scenes

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/80)

### CODE REVIEW

**Review by chrisochoatri — COMMENTED** [review]
+@quincy-kh-chen feature review

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/80#-:-MxavnFs03hRQMnwqLYn:b9d0d88)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
Would it be possible to add some documents on auto-label API and directory structure to the proto README? https://github.com/TRI-ML/dgp/blob/master/dgp/proto/README.md

> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/80#-:-Mxex-du2PSypF9duWW5:b-k8r8mn)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @chrisochoatri and @quincy-kh-chen)

___
*[dgp/__init__.py, line 49 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-Mxevx3C7E7A3wH4yF32:-Mxevx3C7E7A3wH4yF33:b-rx8xtc) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/__init__.py#L49)):*
> ```Python
> TRI_DGP_AGENTS_JSON_NAME = "agents_{agent_hash}.json"
> TRI_DGP_AGENTS_SLICES_JSON_NAME = "agents_slices_{slice_hash}.json"
> AUTOLABEL_SCENE_JSON_NAME = 'scene.json'
> ```

BTW add a section for autolabel related constants?
___
*[dgp/datasets/base_dataset.py, line 669 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-MxewZv3CfWw6fXduHT7:-MxewZv3CfWw6fXduHT8:b-9ele1d) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/datasets/base_dataset.py#L669)):*
> ```Python
>                 if k in scene_dir_to_scene
>             }
>             unique_scenes.update(unique_autolabel_scenes)
> ```

What if we have same scenes that both have auto-label and human-annotated labels? Is the auto-label one going to overwrite `unique_scenes`?
___
*[dgp/datasets/base_dataset.py, line 882 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-MxewNeM7Jjrb2lKCt4H:-MxewNeNC1wdDUzFDXyt:b-fafcx3) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/datasets/base_dataset.py#L882)):*
> ```Python
> 
>         autolabel_root: str, default: None
>             Optional path to autolabel root directory
> ```

BTW ending a sentence with a period.



_Code quote:_
```Python
y
```
___
*[dgp/datasets/base_dataset.py, line 1848 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-MxewtkODZZwoGsz9L66:-MxewtkODZZwoGsz9L67:b-xbsqoq) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/datasets/base_dataset.py#L1848)):*
> ```Python
>     requested_autolabels: tuple[str]
>         Tuple of strings of format "<autolabel_model>/<annotation_key>"
>     
> ```

rm space

**Review by chrisochoatri — COMMENTED** [review]
Added a section to the readme.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/80#-:-N0qUf1cAk5imFmLnri5:b-sxrs2d)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen)

___
*[`dgp/datasets/base_dataset.py` line 669 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-MxewZv3CfWw6fXduHT7:-N0qJ9HdBfJokgcO0PZa:b-6q8p1z) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/datasets/base_dataset.py#L669)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

What if we have same scenes that both have auto-label and human-annotated labels? Is the auto-label one going to overwrite `unique_scenes`?
</blockquote></details>

I think this is okay. One of the test cases actually creates this situation (same scene data copied into itself as an autolabel), the ontology table that results has both keys.
___
*[`dgp/datasets/base_dataset.py` line 1848 at r1](https://reviewable.io/reviews/tri-ml/dgp/80#-MxewtkODZZwoGsz9L66:-N0qUceHA8V9IRBjXTn8:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/9ab36dce1368b35c1b69adb906a7fbe04858ff82/dgp/datasets/base_dataset.py#L1848)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

rm space
</blockquote></details>

Done.

**Review by quincy-kh-chen — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/80#-:-N1B9nCN8y2cX16X_LZY:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
