### PR TITLE
schema: add ParallelDomainFrameMetadata for Parallel Domain datasets.

### PR DESCRIPTION
**Pull request by nehalmamgain**
- add protobuf schema for ParallelDomainSampleMetadata
- modify dgp.contribs.pd.metadata to hold sample-level metadata message.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87)

### CODE REVIEW

**Review by tk-woven — COMMENTED** [review]
Can you share the background motivation for this change, please? In particular I'd like to know why we're dealing with "generics" and can't specify a more rigid schema.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N09R7oD1a4UPbPfeDEI:b-kg3uke)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by nehalmamgain** [comment]
Hey Tyler!

We chose to have GenericMetadata because metadata is something that can change over time due to our interest (tags our data scientists are interested in for AL/auto-labeling) and the heterogeneity of sensors. We'd much rather that metadata exist as key, value pairs than have field numbers which could possibly be a pain to maintain backward-compatibility with over time.

**Review by kuanleetri — APPROVED** [review]
I missed the discussion thread but would it be clearer if putting `map<string, string> metadata` under `ParallelDomainSceneMetadata` (and use more specific name instead of `metadata`)?

I assume almost all message in `ParallelDomainSceneMetadata` will be reused, right?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N09WUAY-_m6mcDRMsT6:bve4c6p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Review by tk-woven — COMMENTED** [review]
Thanks for clarifying, Nehal! The current design will have people develop opaque (have to check the source code of whatever sends/receives the messages) protocols based on specific string values. We currently suffer from this with various tools of ours, and it's something I'd like to avoid if possible.

> maintain backward-compatibility with over time

Protocol buffers are specifically designed with [this use case](https://developers.google.com/protocol-buffers/docs/proto#updating) in mind. Do we anticipate changing the schema so often that this feature does not suit our needs?

For heterogeneous sensors, could we not have a [repeated](https://developers.google.com/protocol-buffers/docs/proto#updating) sensor message type that leverages [one_of](https://developers.google.com/protocol-buffers/docs/proto#using-oneof), options being messages unique to whatever unique sensors we have?

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N09VjJI9Jxl8viPcLta:b9coe2s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Comment by nehalmamgain** [comment]
Hi Kuan!
Thanks for your comments!

I imagine it's some other Parallel Domain dataset (I don't know which - maybe James or Quincy could tell) that uses the messages currently on this repository under metadata.proto. Those metadata are not at all used in another dataset of interest we have (for lane lines).
Let me share specifically what the metadata looks like with you and Tyler over Slack. 

@tk-woven 
> Do we anticipate changing the schema so often that this feature does not suit our needs?
Unfortunately, yes. There are a lot of tags in our initial request (which PD cannot render right now and we have an even more detailed one (~200) for the real dataset). As PD's assets mature, the metadata can definitely grow into more fine-grained options.

**Review by tk-woven — COMMENTED** [review]
It sounds like we'll mostly be adding fields. Is this right? If so, I don't see why we are not leveraging protobuf's support for evolving definitions. Growing a message is a very natural thing.

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N09ec4t3IR_yb0-mg-S:b-7aipw8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Comment by nehalmamgain** [comment]
Sorry, continuing the discussion on Slack to discuss specifics, since this is public repo 🙁

**Review by kuanleetri — APPROVED** [review]
@nehalmamgain per discussion can we put `country` , `time_of_day`, `weather` under `ParallelDomainSceneMetadata` and map<string, string> attributes for others?

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N0Dm5zu7f3Rziy1Yboj:b23nz9i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Comment by nehalmamgain** [comment]
@kuanleetri Yes, as per the schema we agreed upon on Slack, I will take that to PD. Thank you!
Waiting on Quincy's comments for any further changes.

**Review by kuanleetri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87)* status: all files reviewed, 2 unresolved discussions (waiting on @nehalmamgain)

___
*[`dgp/contribs/pd/metadata.proto` line 28 at r2](https://reviewable.io/reviews/tri-ml/dgp/87#-N0b-QWJ5-bagyxuKRs4:-N0b-QWJ5-bagyxuKRs5:b-uuaiyt) ([raw file](https://github.com/tri-ml/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L28)):*
> ```protobuf
> 
> // Frame-level metadata to encode attribute information in key-value pairs.
> message ParallelDomainFrameMetadata {
> ```

Prefer to use `Sample` instead of `Frame`
btw, I thought there're some relatively stable variabls like `weather` can be explicitly list here (if no that's fine).
___
*[`dgp/contribs/pd/metadata.proto` line 79 at r2](https://reviewable.io/reviews/tri-ml/dgp/87#-N0b0GH_Czp7zsspiwX_:-N0b0GH_Czp7zsspiwXa:b-f9gji7) ([raw file](https://github.com/tri-ml/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L79)):*
> ```protobuf
>   // Batch ID and version for delivery tracking
>   uint32 batch_id = 7;
>   uint32 version = 8;
> ```

Do you need?
```repeat ParallelDomainSampleMetadata sample_metadata```

**Review by quincy-kh-chen — APPROVED** [review]
:lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N0c6X9J1Aq_k0V4kfmF:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @nehalmamgain)

**Review by quincy-kh-chen — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87)* status: all files reviewed, 2 unresolved discussions (waiting on @nehalmamgain)

___
*[`dgp/contribs/pd/metadata.proto` line 2 at r2](https://reviewable.io/reviews/tri-ml/dgp/87#-N0c6trJ3cHshuG9oNrl:-N0c6trJ3cHshuG9oNrm:b8leudt) ([raw file](https://github.com/tri-ml/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L2)):*
> ```protobuf
> // Copyright 2020 Parallel Domain.  All rights reserved.
> // Definitions for Parallel Domain Scene-level and Frame-level Metadata
> ```

FYI `Sample-level`?



_Code quote:_
```protobuf
Frame
```

**Review by nehalmamgain — COMMENTED** [review]
Got you both, will make the change for `Frame` -> `Sample`

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N0cNFhxEo4yHQD-gdtn:b-jnswul)* status: all files reviewed, 2 unresolved discussions (waiting on @kuanleetri)

___
*[`dgp/contribs/pd/metadata.proto` line 28 at r2](https://reviewable.io/reviews/tri-ml/dgp/87#-N0b-QWJ5-bagyxuKRs4:-N0cIwLE2_kG90N7r5hy:b-mnj9qf) ([raw file](https://github.com/tri-ml/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L28)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Prefer to use `Sample` instead of `Frame`
btw, I thought there're some relatively stable variabls like `weather` can be explicitly list here (if no that's fine).
</blockquote></details>

Right, so regarding the weather, that will be encoded in `ParallelDomainSceneMetadata` [here](https://github.com/TRI-ML/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L63-L72), so we don't need to include it for sample level metadata.
___
*[`dgp/contribs/pd/metadata.proto` line 79 at r2](https://reviewable.io/reviews/tri-ml/dgp/87#-N0b0GH_Czp7zsspiwX_:-N0cJQMO1hioPcMMhZWK:bqmqy37) ([raw file](https://github.com/tri-ml/dgp/blob/c6c8dca75c4c74f3286acb0bb4c2cb78d1d4ee04/dgp/contribs/pd/metadata.proto#L79)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Do you need?
```repeat ParallelDomainSampleMetadata sample_metadata```
</blockquote></details>

Thanks Kuan, I took your suggestion to PD, and they do not want nested proto schema and unnecessary depth.
I can add an attributes field here too though.

**Review by kuanleetri — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Review by kuanleetri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/87#-:-N0cUy1m88m83BsL47LQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nehalmamgain)

**Pull request merged**
