### PR TITLE
schema: modify segmentation 3d schema with point_index

### PR DESCRIPTION
**Pull request by rachel-lien**
This change is [Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/152)

### CODE REVIEW

**Review by rachel-lien — COMMENTED** [review]
+@yuta-tsuzuki-woven please review 

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/152#-:-NVbS1kn5gIi4s5ljWFp:b-daxubx)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @yuta-tsuzuki-woven)

**Review by KMilhan — COMMENTED** [review]
Could you please tell me if my understanding is correct?
* current implementation is difficult to establish a healthy connection to the data 
* This change adds a linkage to the original data so we don't need to duplicate or misalign data

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/152#-:-NVc2GAv6id1AuEThZtv:b-i8g5ut)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @yuta-tsuzuki-woven)

**Review by rachel-lien — COMMENTED** [review]
>-   current implementation is difficult to establish a healthy connection to the data

Yes, the current implementation can be difficult to map output (annotation) back to input (point cloud)


>-   This change adds a linkage to the original data so we don't need to duplicate or misalign data

This change adds a linkage to the original data, but it does not solve any issues with duplication or misaligned data.

> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/152#-:-NVekI20-pHnHrJLjvwa:bgyn63y)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachel-lien)

**Review by KMilhan — COMMENTED** [review]
LGTM

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/TRI-ML/dgp/152#-:-NVgC2gp4gf4x-iCLCBS:bb6ywmx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rachel-lien)

**Pull request merged**
