### PR TITLE
docs: update proto readme

### PR DESCRIPTION
**Pull request by visakii-work**
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)

### CODE REVIEW

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/proto/README.md, line 2 at r1](https://reviewable.io/reviews/tri-ml/dgp/66#-Mpmng9BDiKmY5yLmm_f:-Mpmng9C-y6Bs2d3OkjL:b-bfye05) ([raw file](https://github.com/tri-ml/dgp/blob/158203ff383c707ab569e9c44bba480af5518ae0/dgp/proto/README.md#L2)):*
> ```
> ==========
> ```
Let's refactor this README to `# ## ###` style. Thank you.

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/proto/README.md, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/66#-MpmnqY64ykPIkDxqCYt:-MpmnqY64ykPIkDxqCYu:b8q75t2) ([raw file](https://github.com/tri-ml/dgp/blob/158203ff383c707ab569e9c44bba480af5518ae0/dgp/proto/README.md#L14)):*
> ```Markdown
> * Datum: A Datum encapsulates sensory data (image, point cloud, radar point cloud, etc),
> along with their associated annotations.
> * AgentDataset: Dataset for agent-centric prediction or planning use cases,but guaranteeing
> ```

Let's add an additional session for Agent data structure description, to make it additional to the original `SceneDataset` description.

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @visakii-work)

___
*[dgp/proto/README.md, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/66#-MpmnqY64ykPIkDxqCYt:-MpmoDDk2I_vLUMWoUxz:b-pdumq0) ([raw file](https://github.com/tri-ml/dgp/blob/158203ff383c707ab569e9c44bba480af5518ae0/dgp/proto/README.md#L14)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's add an additional session for Agent data structure description, to make it additional to the original `SceneDataset` description.
</blockquote></details>

Let's also explain what's `AgentGroup`, `AgentSnapshot`, `AgentsSlice`. Replicating the comments from proto is okay.

**Review by visakii-work — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ChaoFang-TRI and @quincy-kh-chen)

___
*[dgp/proto/README.md, line 2 at r1](https://reviewable.io/reviews/tri-ml/dgp/66#-Mpmng9BDiKmY5yLmm_f:-Mr3qZno0BIotWj-nBiU:b-a2ujfl) ([raw file](https://github.com/tri-ml/dgp/blob/158203ff383c707ab569e9c44bba480af5518ae0/dgp/proto/README.md#L2)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

> ```
> ==========
> ```
Let's refactor this README to `# ## ###` style. Thank you.
</blockquote></details>

Changed.
___
*[dgp/proto/README.md, line 14 at r1](https://reviewable.io/reviews/tri-ml/dgp/66#-MpmnqY64ykPIkDxqCYt:-Mr3qallAdLs2jrkDeiv:b-uaydl5) ([raw file](https://github.com/tri-ml/dgp/blob/158203ff383c707ab569e9c44bba480af5518ae0/dgp/proto/README.md#L14)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's also explain what's `AgentGroup`, `AgentSnapshot`, `AgentsSlice`. Replicating the comments from proto is okay.
</blockquote></details>

Added description.

**Review by ChaoFang-TRI — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66#-:-Mr8c9sB7Jpik2-H0iFx:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @quincy-kh-chen)

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: all files reviewed, 12 unresolved discussions (waiting on @visakii-work)

___
*[dgp/proto/README.md, line 5 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mLcJ0qsRwLHXOWEo:-Mr8mLcJ0qsRwLHXOWEp:b30t2zu) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L5)):*
> ```Markdown
> DGP-compliant datasets follow the structure and schema defined in this directory. Top-level
> data containers are listed below:
> ```

Let's add a header `## SceneDataset data structure description`
___
*[dgp/proto/README.md, line 16 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mvg_CTXc5Z53cREm:-Mr8mvg_CTXc5Z53cREn:bbljfem) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L16)):*
> ```Markdown
> 
> 
> ## AgentDataset Description
> ```

AgentDataset data structure description?
___
*[dgp/proto/README.md, line 18 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mhho60Mdw3QO15PQ:-Mr8mhho60Mdw3QO15PR:bnc4uhd) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L18)):*
> ```Markdown
> ## AgentDataset Description
> * AgentDataset: Dataset for agent-centric prediction or planning use cases,but guaranteeing trajectory of main agent is present in any fetched sample.
> * AgentSnapshot: Takes values from one of agent types AgentSnapshot3D or AgentSnapshot2D.
> ```

Let's elaborate what's the difference between AgentSnaphot and AgentSnapshot3D/2D e.g. what're the extra fields



_Code quote:_
```Markdown
* AgentSnapshot: Takes values from one of agent types AgentSnapshot3D or AgentSnapshot2D.
```
___
*[dgp/proto/README.md, line 31 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8n68C-uTgajKvzgnq:-Mr8n68C-uTgajKvzgnr:b-s6i0iz) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L31)):*
> ```Markdown
> directory. Schema for the following types are specified their
> corresponding `proto` files.
> * Annotations and Annotation Types: [`annotations.proto`](./annotations.proto)
> ```

alphabetical order 



_Code quote:_
```Markdown
* Annotations and Annotation Types: [`annotations.proto`](./annotations.proto)
* Dataset Artifacts: [`artifacts.proto`](./artifacts.proto)
* Dataset Provenance / Tracking: [`identifiers.proto`](./identifiers.proto)
* Dataset: [`dataset.proto`](./dataset.proto)
* Image container: [`image.proto`](./image.proto)
* PointCloud container: [`point_cloud.proto`](./point_cloud.proto)
* Radar PointCloud container: [`radar_point_cloud.proto`](./radar_point_cloud.proto)
* Remote Storage: [`remote.proto`](./remote.proto)
* Agent: [`agent.proto`](./agent.proto)
* Features: [`features.proto`](./features.proto)
* Ontology: [`ontology.proto`](./ontology.proto)
```
___
*[dgp/proto/README.md, line 88 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nicd84PUdWL8LYwN:-Mr8nicd84PUdWL8LYwO:b-oq8niv) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L88)):*
> ```Markdown
> Agents are stored in the DGP under the following structure:
> ``` text
> 📦dataset_root_dir
> ```

to be consistent -> <dataset_root_dir>



_Code quote:_
```Markdown
dataset_root_dir
```
___
*[dgp/proto/README.md, line 88 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nqqjCP9cxgpvBVh2:-Mr8nqqjCP9cxgpvBVh3:bodqg7l) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L88)):*
> ```Markdown
> Agents are stored in the DGP under the following structure:
> ``` text
> 📦dataset_root_dir
> ```

BTW does this emoji has any meaning?
___
*[dgp/proto/README.md, line 89 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nmzjBJsvs6L46hgi:-Mr8nmzjBJsvs6L46hgj:b-7ropln) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L89)):*
> ```Markdown
> ``` text
> 📦dataset_root_dir
>  ┣ 📂scene_name
> ```

ditto
___
*[dgp/proto/README.md, line 94 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nVBR7zsdH4b8LxOQ:-Mr8nVBR7zsdH4b8LxOR:bkrr9z) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L94)):*
> ```Markdown
>  ┃ ┃ ┗ 📜agents_slices_<agent_hash>.json
>  ┃ ┣ 📂bounding_box_2d
>  ┃ ┃ ┣ 📂CAMERA_NAME
> ```

to be consistent -> <camera_name>



_Code quote:_
```Markdown
<camera_name>
```
___
*[dgp/proto/README.md, line 99 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nX9S3PPW_MXnam8q:-Mr8nX9S3PPW_MXnam8r:b-7ropln) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L99)):*
> ```Markdown
>  ┃ ┃ ┗ .. 
>  ┃ ┣ 📂bounding_box_3d
>  ┃ ┃ ┣ 📂CAMERA_NAME
> ```

ditto
___
*[dgp/proto/README.md, line 103 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nXxbCqFgWgGu3SsO:-Mr8nXxbCqFgWgGu3SsP:bt4gvla) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L103)):*
> ```Markdown
>  ┃ ┃ ┃ ┗ ..
>  ┃ ┃ ┗ ..
>  ┃ ┃ ┗ 📂LIDAR_NAME
> ```

to be consistent -> <lidar_name>
___
*[dgp/proto/README.md, line 113 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8n_nSCWsLF5Q1JlLz:-Mr8n_nSCWsLF5Q1JlM-:b-7ropln) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L113)):*
> ```Markdown
>  ┃ ┃ ┗ 📜<ontology_hash>.json
>  ┃ ┣ 📂point_cloud
>  ┃ ┃ ┗ 📂LIDAR
> ```

ditto
___
*[dgp/proto/README.md, line 117 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nafj2Nf52vf_OEfh:-Mr8nafj2Nf52vf_OEfi:b-7ropln) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L117)):*
> ```Markdown
>  ┃ ┃ ┃ ┗ ..
>  ┃ ┣ 📂rgb
>  ┃ ┃ ┣ 📂CAMERA_NAME
> ```

ditto
___
*[dgp/proto/README.md, line 123 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8ncfqDB4Vmw1E-Q9G:-Mr8ncfqDB4Vmw1E-Q9H:b8jvm1k) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L123)):*
> ```Markdown
>  ┃ ┣ 📜agents_<agent_hash>.json
>  ┃ ┗ 📜scene_<scene_hash>.json
>  ┣ 📜agents_pcc_mini_v<version>.json
> ```

We always have `pcc_mini`? -> agents_<task>_v<version>.json ?



_Code quote:_
```Markdown
pcc_mini
```

**Review by visakii-work — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)

___
*[dgp/proto/README.md, line 5 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mLcJ0qsRwLHXOWEo:-MrOUn8JC8_SVoq4EMKd:b-t948zx) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L5)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's add a header `## SceneDataset data structure description`
</blockquote></details>

added.
___
*[dgp/proto/README.md, line 16 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mvg_CTXc5Z53cREm:-MrOUpGX8aQbbS0zVTPW:b-pebltl) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L16)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

AgentDataset data structure description?
</blockquote></details>

yes, that is more complete. made the change
___
*[dgp/proto/README.md, line 18 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8mhho60Mdw3QO15PQ:-MrOUsz64FXp7ioyzdH0:b-1jxd0q) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L18)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

Let's elaborate what's the difference between AgentSnaphot and AgentSnapshot3D/2D e.g. what're the extra fields
</blockquote></details>

I elaborated this .lmk if it makes sense.
___
*[dgp/proto/README.md, line 31 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8n68C-uTgajKvzgnq:-MrOUw0f7W3_mK6o6mNU:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L31)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

alphabetical order 
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 88 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nicd84PUdWL8LYwN:-MrOUxX-DzHkPEi0n8De:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L88)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

to be consistent -> <dataset_root_dir>
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 88 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nqqjCP9cxgpvBVh2:-MrOUxtz2hKZ3EW5-Sjb:bq39i75) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L88)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

BTW does this emoji has any meaning?
</blockquote></details>

So, I think its just emoji for root_dir/folder or a file. I used a extension with VS code to get this structure. We can just use the older format if you think this is confusing.
___
*[dgp/proto/README.md, line 89 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nmzjBJsvs6L46hgi:-MrOV9zA1x29hpkjaaYP:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L89)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 94 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nVBR7zsdH4b8LxOQ:-MrOVASuEbIqOgerVA0U:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L94)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

to be consistent -> <camera_name>
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 99 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nX9S3PPW_MXnam8q:-MrOVAkB6srI82S8oQ9M:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L99)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 113 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8n_nSCWsLF5Q1JlLz:-MrOVB7k4t7kie8KOCQA:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L113)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 123 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8ncfqDB4Vmw1E-Q9G:-MrOVBel5U9_1nWOiPqz:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L123)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

We always have `pcc_mini`? -> agents_<task>_v<version>.json ?
</blockquote></details>

Done.

**Review by quincy-kh-chen — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: all files reviewed, 4 unresolved discussions (waiting on @quincy-kh-chen and @visakii-work)

___
*[dgp/proto/README.md, line 94 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nVBR7zsdH4b8LxOQ:-MsgDPiO08dABttJqROm:bp76pxb) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L94)):*
<details><summary><i>Previously, visakii-work wrote…</i></summary><blockquote>

Done.
</blockquote></details>

lower case `<camera_name>` to be consistent with the `DGP SceneDataset Structure` above
___
*[dgp/proto/README.md, line 21 at r4](https://reviewable.io/reviews/tri-ml/dgp/66#-MsgCp7EDq6vqkGUOi-m:-MsgCp7EDq6vqkGUOi-n:b431gg8) ([raw file](https://github.com/tri-ml/dgp/blob/48ba20d5ca59b1bf91f07af02c55c848fc2effe6/dgp/proto/README.md#L21)):*
> ```Markdown
> 
> * AgentDataset: Dataset for agent-centric prediction or planning use cases,but guaranteeing trajectory of main agent is present in any fetched sample.
> * AgentSnapshot: An Agent in a Scene can be represented by either an AgentSnapshot2D or AgentSnapshot3D. If it is AgentSnaphot3D, then the agent is represented as a 3DBoundingBox along with other fields such as features, instance id's, etc. In case it is represented as AgentSnapshot2D, then a 2D BoundingBox is used.
> ```

`BoundingBox3D` to be consistent with our proto schema: https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L111



_Code quote:_
```Markdown
3DBoundingBox
```
___
*[dgp/proto/README.md, line 21 at r4](https://reviewable.io/reviews/tri-ml/dgp/66#-MsgD6X5Cr5deo345y54:-MsgD6X5Cr5deo345y55:bxui6mb) ([raw file](https://github.com/tri-ml/dgp/blob/48ba20d5ca59b1bf91f07af02c55c848fc2effe6/dgp/proto/README.md#L21)):*
> ```Markdown
> 
> * AgentDataset: Dataset for agent-centric prediction or planning use cases,but guaranteeing trajectory of main agent is present in any fetched sample.
> * AgentSnapshot: An Agent in a Scene can be represented by either an AgentSnapshot2D or AgentSnapshot3D. If it is AgentSnaphot3D, then the agent is represented as a 3DBoundingBox along with other fields such as features, instance id's, etc. In case it is represented as AgentSnapshot2D, then a 2D BoundingBox is used.
> ```

`BoundingBox2D` to be consistent with our proto schema: https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L72



_Code quote:_
```Markdown
2D BoundingBox
```

**Review by visakii-work — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @quincy-kh-chen)

___
*[dgp/proto/README.md, line 103 at r2](https://reviewable.io/reviews/tri-ml/dgp/66#-Mr8nXxbCqFgWgGu3SsO:-MsgJjgBBmJTGeh-0PGh:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/42cccda04a33fad4a13176bd34afa1126de17bcb/dgp/proto/README.md#L103)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

to be consistent -> <lidar_name>
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 21 at r4](https://reviewable.io/reviews/tri-ml/dgp/66#-MsgD6X5Cr5deo345y54:-MsgJlOB6bMnAdtvW_hB:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/48ba20d5ca59b1bf91f07af02c55c848fc2effe6/dgp/proto/README.md#L21)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`BoundingBox2D` to be consistent with our proto schema: https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L72
</blockquote></details>

Done.
___
*[dgp/proto/README.md, line 21 at r4](https://reviewable.io/reviews/tri-ml/dgp/66#-MsgCp7EDq6vqkGUOi-m:-MsgJldR5fzP46N3aHRd:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/48ba20d5ca59b1bf91f07af02c55c848fc2effe6/dgp/proto/README.md#L21)):*
<details><summary><i>Previously, quincy-kh-chen (quincy.chen) wrote…</i></summary><blockquote>

`BoundingBox3D` to be consistent with our proto schema: https://github.com/TRI-ML/dgp/blob/master/dgp/proto/annotations.proto#L111
</blockquote></details>

Done.

**Review by quincy-kh-chen — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66#-:-MsgM5bq96U1ULjUeXMo:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @visakii-work)

**Review by quincy-kh-chen — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @visakii-work)

**Pull request merged**
