### PR TITLE
feat: add distortion parameters to BaseDataset

### PR DESCRIPTION
**Pull request by chrisochoatri**
This adds a new key to the fields returned by base dataset. The key 'distortion' contains a dictionary with the distortion parameters set in the camera intrinsics proto. This requires [PR 86](https://reviewable.io/reviews/TRI-ML/dgp/86#-) to be merged first.

---
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)

### CODE REVIEW

**Review by kuanleetri — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: all files reviewed, 4 unresolved discussions (waiting on @chrisochoatri)

___
*[dgp/datasets/base_dataset.py, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E3rdw2PJgEGh9NSp5:-N0E3rdw2PJgEGh9NSp6:b-oqtwjw) ([raw file](https://github.com/tri-ml/dgp/blob/d060e7d495363b5c652be2360b16188e93e85531/dgp/datasets/base_dataset.py#L37)):*
> ```Python
> 
> AVAILABLE_DATUM_TYPES = ("image", "point_cloud")
> AVAILABLE_DISTORTION_PARAMS = [
> ```

use tuple for consistency?
___
*[dgp/datasets/base_dataset.py, line 960 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E6YNjAfUiRCKm64Sz:-N0E6YNjAfUiRCKm64T-:b-ha33wv) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/datasets/base_dataset.py#L960)):*
> ```Python
>                 # assumed to be a LIDAR sensor.
> 
>                 # TODO: refactor this
> ```

describe clearly about how to refactor?
___
*[dgp/utils/camera.py, line 57 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E6MBx0TMM-UBZfOWw:-N0E6MByEIMQ1j7F50kR:b-8o4ypi) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/utils/camera.py#L57)):*
> ```Python
> 
>     distortion: dict[str, float]
>             Dictionary of distortion params i.e, k1,k2,p1,p2,k3,k4,xi,alpha etc
> ```

consistent indent?
___
*[dgp/utils/camera.py, line 187 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E5bVc1eonBKieJlQd:-N0E5bVc1eonBKieJlQe:b6dvlse) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/utils/camera.py#L187)):*
> ```Python
>             [0, 0, 1],
>         ])
>         return cls(K=K, D = distortion, p_cw=p_cw)
> ```

probably no space around `=`?

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @kuanleetri)

___
*[dgp/datasets/base_dataset.py, line 37 at r1](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E3rdw2PJgEGh9NSp5:-N0E9w6SApE7oTfndQfd:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/d060e7d495363b5c652be2360b16188e93e85531/dgp/datasets/base_dataset.py#L37)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

use tuple for consistency?
</blockquote></details>

Done.
___
*[dgp/datasets/base_dataset.py, line 960 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E6YNjAfUiRCKm64Sz:-N0EA11J8K7dK6tjX8no:blan5w2) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/datasets/base_dataset.py#L960)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

describe clearly about how to refactor?
</blockquote></details>

Added a bit more. But really the entire Camera class need to be refactored. The Distortion part of the camera class was never fully implemented and it only supported the Brown Conrady model. If we change that, we need to change the project/unproject methods also etc.
___
*[dgp/utils/camera.py, line 57 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E6MBx0TMM-UBZfOWw:-N0EAOKkBIXcHd48QhVi:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/utils/camera.py#L57)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

consistent indent?
</blockquote></details>

Done.
___
*[dgp/utils/camera.py, line 187 at r2](https://reviewable.io/reviews/tri-ml/dgp/88#-N0E5bVc1eonBKieJlQd:-N0EAP2Y18KUaHpVfOK2:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/590d51dff9906f6d268a6a167e577c23469b7789/dgp/utils/camera.py#L187)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

probably no space around `=`?
</blockquote></details>

Done.

**Review by kuanleetri — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88#-:-N0GpwyuDPDc_IjYTClL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

___
*[dgp/proto/geometry.proto, line 44 at r3](https://reviewable.io/reviews/tri-ml/dgp/88#-N0GqI8Y6tbwttmgzUHn:-N0GqI8Y6tbwttmgzUHo:b-9xnuq0) ([raw file](https://github.com/tri-ml/dgp/blob/f521439da749c2287370483c0a0845627f6e949d/dgp/proto/geometry.proto#L44)):*
> ```protobuf
>   double skew = 5;
> 
>   // Camera distortion parameters, copied over from Parallel Domain
> ```

@quincy-kh-chen I think this is related to the discussion about either we want use `map<string, string> distortions` for flexibility or list out everything like this. Since this is in master proto, what's your suggestion here?

**Review by kuanleetri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

**Review by kuanleetri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @kuanleetri and @quincy-kh-chen)

___
*[dgp/proto/geometry.proto, line 44 at r3](https://reviewable.io/reviews/tri-ml/dgp/88#-N0GqI8Y6tbwttmgzUHn:-N0GxFdE-JuU8SAvY0va:b-cn7tcg) ([raw file](https://github.com/tri-ml/dgp/blob/f521439da749c2287370483c0a0845627f6e949d/dgp/proto/geometry.proto#L44)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

@quincy-kh-chen I think this is related to the discussion about either we want use `map<string, string> distortions` for flexibility or list out everything like this. Since this is in master proto, what's your suggestion here?  
</blockquote></details>

@kuanleetri The challenge is backward compatibility with Parallel Domain, better to discuss this on the first PR here: https://reviewable.io/reviews/TRI-ML/dgp/86#-

**Review by kuanleetri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
