### PR TITLE
feat: add camera datum augmentations

### PR DESCRIPTION
**Pull request by chrisochoatri**
This adds additional transformations for working with camera datums and transforming (most) annotations in a consistent manner. This simplifies lots of data pre-processing and augmentation work by consuming datums formatted as the output of a SychronizedScene, and returning new datums.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)

### CODE REVIEW

**Review by chrisochoatri — COMMENTED** [review]
+@kuanleetri can you review this one?

cc @wadimkehl  @tk-woven 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMIVv7-W-yy1QcgYxy:bdxnomv)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @kuanleetri)

**Review by tk-woven — CHANGES_REQUESTED** [review]
Thanks Chris! Some comments, mostly on cosmetic stuff :)

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMR2iZ73oEE8m1HfmW:byl1miz)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri and @kuanleetri)

___
*[`dgp/annotations/camera_transforms.py` line 33 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMKJ1M6PWO5SDgzvhx:-NAMKJ1M6PWO5SDgzvhy:bfp3d6q) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L33)):*
> ```Python
> 
> # Some opencv operations can lead to deadlocks when using multiprocess.fork instead of spawn
> # we disable opencv multithreading to be safe
> ```

I suspect this will change the behavior of downstream users that import DGP and cv2 in their projects. It's not clear to me exactly what impact this might have, though, so just an FYI.
___
*[`dgp/annotations/camera_transforms.py` line 75 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMLbdq2e2ov6gOTSWo:-NAMLbdq2e2ov6gOTSWp:bykz3mb) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L75)):*
> ```Python
> 
>     # Rotate and scale
>     # TODO: break scale into scale_y and scale_x?
> ```

Can you please attribute the TODO (ex: `TODO(chrisochoatri)`) here and for the other TODOs in this work?
___
*[`dgp/annotations/camera_transforms.py` line 109 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMM6OOBOXsbF3oQYyv:-NAMM6OOBOXsbF3oQYyw:b-22pys9) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L109)):*
> ```Python
>         Box corners expressed as x1,y1,x2,y2.
>     target_shape: tuple
>         Desired image shape after cropping and resizing.
> ```

Let's specify the order, ex `h, w`, please. There are some other tuples in new docs here that I think we should apply this to as well.
___
*[`dgp/annotations/camera_transforms.py` line 490 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMNZ4b61e7OFpMhfXz:-NAMNZ4cCUJGRoMNw8FY:bqo6rzw) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L490)):*
> ```Python
>                                                      mode=cv2.INTER_NEAREST).astype(np.bool)
> 
>             # TODO: how to treat zero mass results? ie if after a transformation,
> ```

Maybe we mean "mask."



_Code quote:_
```Python
mass
```
___
*[`dgp/annotations/camera_transforms.py` line 513 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMNias7vhPvvze16L2:-NAMNias7vhPvvze16L3:b-4fdvc6) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L513)):*
> ```Python
> 
>         if mask is None:
>             return None
> ```

Because we can return `None`, let's declare our return type as `Optional[np.ndarray]` and document the conditions that would cause us to return `None`, please.
___
*[`dgp/annotations/camera_transforms.py` line 535 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMO2ArEPC0NvR6N1TH:-NAMO2ArEPC0NvR6N1TI:b-oavyyv) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L535)):*
> ```Python
>             List of transformed bounding keypoint annotations.
>         """
>         logger.warning('keypoints not yet been tested, please use caution using this')
> ```

I have to ask, when do we plan on adding tests for this? :) It seems a bit of a risky gamble to me if end users use this and don't bother to read the printed warnings for whatever reason.
___
*[`dgp/annotations/camera_transforms.py` line 565 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMOiPB10XSSvGCuKEJ:-NAMOiPB10XSSvGCuKEK:bo5daca) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L565)):*
> ```Python
>         assert cam_datum['datum_type'] == 'image', 'expected an image datum_type'
> 
>         assert 'rgb' in cam_datum, 'datum should contain an image'
> ```

Since these `asserts` are checking input requirements, could you please document these requirements in the method docs? This might not be the norm in many other places in DGP, but I'd like to move toward this for end-user convenience.
___
*[`tests/test_camera_transforms.py` line 24 at r1](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMQDQ-Bg5ngMcpQ9EL:-NAMQDQ-Bg5ngMcpQ9EM:btuaw0b) ([raw file](https://github.com/tri-ml/dgp/blob/365eedc82123299aceff0acb8f7e9b0279485de8/tests/test_camera_transforms.py#L24)):*
> ```Python
> 
> 
> def assert_almost_mostly_equal(datum1, datum2, valid_region=None):
> ```

How about `assert_almost_equal`? This would follow the convention used in things like unittest and numpy.

**Review by kuanleetri — CHANGES_REQUESTED** [review]
It's a bit huge commit...bare with me to review it slowly...

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMXKvo-9s_sLW43WRD:b-dvcqjy)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri)

___
*[`dgp/annotations/camera_transforms.py` line 33 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMKJ1M6PWO5SDgzvhx:-NAMWUai1h0_4Q8_zJFq:b-b7vyjd) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L33)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

I suspect this will change the behavior of downstream users that import DGP and cv2 in their projects. It's not clear to me exactly what impact this might have, though, so just an FYI.
</blockquote></details>

Agree, possible to set number back after the deadlock section?

**Review by tk-woven — CHANGES_REQUESTED** [review]
Thanks for the update, Chris! One doc nit leftover, but otherwise looks good to me.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMjozRE71UTOmOiEOj:b-94cqjg)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

___
*[`dgp/annotations/camera_transforms.py` line 513 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMNias7vhPvvze16L2:-NAMjLVOBvoHrGayXmWQ:bkqthqu) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L513)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Because we can return `None`, let's declare our return type as `Optional[np.ndarray]` and document the conditions that would cause us to return `None`, please.
</blockquote></details>

Sorry, I should have also noted that we'll have to update the documented return type too. Could we do that as well please?

**Review by tk-woven — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: all files reviewed, 1 unresolved discussion (waiting on @chrisochoatri)

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-woven)

___
*[`dgp/annotations/camera_transforms.py` line 33 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMKJ1M6PWO5SDgzvhx:-NAMeSwr22hn0ZFduLm_:bpywo5h) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L33)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

Agree, possible to set number back after the deadlock section?
</blockquote></details>

I just changed it to a note
___
*[`dgp/annotations/camera_transforms.py` line 75 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMLbdq2e2ov6gOTSWo:-NAMeWOXE15OrCJF2ZGl:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L75)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Can you please attribute the TODO (ex: `TODO(chrisochoatri)`) here and for the other TODOs in this work?
</blockquote></details>

Done.
___
*[`dgp/annotations/camera_transforms.py` line 109 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMM6OOBOXsbF3oQYyv:-NAMeXPX24SOSEKzLJR-:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L109)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Let's specify the order, ex `h, w`, please. There are some other tuples in new docs here that I think we should apply this to as well.
</blockquote></details>

Done.
___
*[`dgp/annotations/camera_transforms.py` line 513 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMNias7vhPvvze16L2:-NAMef5PBVRP-xhtq52I:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L513)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Because we can return `None`, let's declare our return type as `Optional[np.ndarray]` and document the conditions that would cause us to return `None`, please.
</blockquote></details>

Done.
___
*[`dgp/annotations/camera_transforms.py` line 535 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMO2ArEPC0NvR6N1TH:-NAMegM7DtLlLamlRIsW:bv6w64j) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L535)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

I have to ask, when do we plan on adding tests for this? :) It seems a bit of a risky gamble to me if end users use this and don't bother to read the printed warnings for whatever reason.
</blockquote></details>

Thanks this was a bit old. I basically was waiting for a dataset that had keypoints. I created some fake data to test, removed the warning.
___
*[`dgp/annotations/camera_transforms.py` line 565 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMOiPB10XSSvGCuKEJ:-NAMew693JTqX-gSTI-H:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L565)):*
<details><summary><i>Previously, tk-woven wrote…</i></summary><blockquote>

Since these `asserts` are checking input requirements, could you please document these requirements in the method docs? This might not be the norm in many other places in DGP, but I'd like to move toward this for end-user convenience.
</blockquote></details>

Done.

**Review by chrisochoatri — COMMENTED** [review]
Thanks Tyler, think I got to most of them. 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMoYPN8RUFJm2ZmObK:btibwds)* status: all files reviewed, 1 unresolved discussion (waiting on @tk-woven)

**Review by tk-woven — DISMISSED** [review]
Thanks :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAMpyIL00abBmtTj7hM:b5euyw2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

___
*[`dgp/annotations/camera_transforms.py` line 513 at r2](https://reviewable.io/reviews/tri-ml/dgp/126#-NAMNias7vhPvvze16L2:-NAMpRB07YDfjXHyagaQ:bsya3q3) ([raw file](https://github.com/tri-ml/dgp/blob/b2e15b1dd0800c897b909f50a212f1c2378c802c/dgp/annotations/camera_transforms.py#L513)):*
<details><summary><i>Previously, chrisochoatri (Chris Ochoa) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! We fixed the annotations, but I meant that we also need to update the return type in the corresponding method docs. But the most important thing is the annotations, so I won't block on this, and we can move on. :)

**Review by kuanleetri — CHANGES_REQUESTED** [review]
in the middle, I'll continue...

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NASn5SaCT_4dOPOcx2O:b-addwa5)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri)

___
*[`dgp/annotations/camera_transforms.py` line 49 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NAQBIl6DU68-vX_qyCt:-NAQBIl6DU68-vX_qyCu:bvki16o) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L49)):*
> ```Python
>     Parameters
>     ----------
> ```

nit: possible to remove 1 empty line under `----------`, just be consistent lol (same as Returns)
___
*[`dgp/annotations/camera_transforms.py` line 105 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NAQBchABc5lqKMYY38U:-NAQBchABc5lqKMYY38V:bblb5ti) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L105)):*
> ```Python
>     Parameters
>     ----------
>     box_xyxy: list or tuple
> ```

I suggest to use top, left bottom, right (like box_tlbr), more explicit.
___
*[`dgp/annotations/camera_transforms.py` line 235 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmCMS-70j3EInM1hi:-NASmCMS-70j3EInM1hj:b-9tql4i) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L235)):*
> ```Python
>             3x3 affine transformation matrix
>         """
>         return self.A
> ```

hmm, if it's just return `self.A`, why u need input?
___
*[`dgp/annotations/camera_transforms.py` line 252 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmMm9ETLrQLNsE2O_:-NASmMm9ETLrQLNsE2Oa:b-5h08c7) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L252)):*
> ```Python
>             new image shape.
>         """
>         return self.shape
> ```

same here.
___
*[`dgp/annotations/camera_transforms.py` line 286 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmmuO-y9Y-1w7TKnj:-NASmmuO-y9Y-1w7TKnk:bhl8tyy) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L286)):*
> ```Python
>                 mode = PIL.Image.BILINEAR
>             elif mode == cv2.INTER_NEAREST:
>                 mode = PIL.Image.NEAREST
> ```

assert for else?
___
*[`dgp/annotations/camera_transforms.py` line 319 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmbJx60-qzyHci5Ct:-NASmbJx60-qzyHci5Cu:bl7eqzu) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L319)):*
> ```Python
>         h, w = self.shape[:2]
> 
>         # Flipping leads to the wrong rotation below, so when there is a flip present, we unflip, do everything, and re flip
> ```

over 120, may be change line? lol

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: all files reviewed, 6 unresolved discussions (waiting on @chrisochoatri and @kuanleetri)

___
*[`dgp/annotations/camera_transforms.py` line 235 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmCMS-70j3EInM1hi:-NAaqU3-0dGP9rq1R31E:byqi2lq) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L235)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

hmm, if it's just return `self.A`, why u need input?
</blockquote></details>

Some derived classes need the input shape to calculate the transform. Like for example scaling an image to a specific height, you need to know the height of the input. Since some transformations need this, and I wanted to make them all composable, then all transformations need to have this api.
___
*[`dgp/annotations/camera_transforms.py` line 252 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmMm9ETLrQLNsE2O_:-NAaqrJlE_895regV7uk:bnj7hl0) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L252)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

same here.
</blockquote></details>

same as above

**Review by chrisochoatri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @kuanleetri and @tk-woven)

___
*[`dgp/annotations/camera_transforms.py` line 105 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NAQBchABc5lqKMYY38U:-NAaut6_8Pr03ZN6flYz:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L105)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

I suggest to use top, left bottom, right (like box_tlbr), more explicit.
</blockquote></details>

Done.
___
*[`dgp/annotations/camera_transforms.py` line 286 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmmuO-y9Y-1w7TKnj:-NAav25s2B7YakcKHb0w:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L286)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

assert for else?
</blockquote></details>

Done.
___
*[`dgp/annotations/camera_transforms.py` line 319 at r4](https://reviewable.io/reviews/tri-ml/dgp/126#-NASmbJx60-qzyHci5Ct:-NAav4xe3DO_3J5_L4r6:b-896fix) ([raw file](https://github.com/tri-ml/dgp/blob/502f93e4dfb42b9c921ab7a53fdc67688448ccfa/dgp/annotations/camera_transforms.py#L319)):*
<details><summary><i>Previously, kuanleetri (Kuan-Hui Lee) wrote…</i></summary><blockquote>

over 120, may be change line? lol
</blockquote></details>

Done.

**Review by tk-woven — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: all files reviewed, 5 unresolved discussions (waiting on @kuanleetri)

**Review by tk-woven — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126)* status: all files reviewed, 5 unresolved discussions (waiting on @kuanleetri)

**Review by kuanleetri — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tri-ml/dgp/126#-:-NAkwVp5A3gr7pWj1r0N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrisochoatri)

**Pull request merged**
